// Biblioteca com métodos para web
const express = require('express');
const bodyParser = require('body-parser');
const app = express();

// DB
const mongodb = require('mongodb');
const MongoClient = mongodb.MongoClient;
var db;
var table = "quotes";

// Usar o midlleware body-parser no express aplication
app.use(bodyParser.urlencoded({extended: true}));

// Usar o midlleware EJS (Embedded JavaScripit) como view engine
app.set('view engine', 'ejs');


app.get('/', (req, res) => {
	res.sendFile(__dirname + '/index.html');
})

var mongoUrlConnection = "mongodb://localhost/quotes";
MongoClient.connect(mongoUrlConnection, (err, database) => {
	if(err)
		return console.error(err);
	db = database;

	// Inicia servidor na porta 3000
	app.listen(3000, function() {
		console.log('listening on port 3000');
	});
});


app.post('/quotes/create', (req, res) => {
	db.collection(table).save(req.body, function(err, result){
		if (err)
			return console.error(err);

		console.log('Salvo no banco de dados!');
		res.redirect('/quotes/list');
	});
	console.log(db);
});

app.get('/quotes/list', (req, res) => {
	var cursor = db.collection(table).find();
	cursor.toArray((err, results) => {
		if (err)
			return console.error(err);

		// NOTA: As view TEM que estar na pasta views
		res.render('list_quotes.ejs', {quotes: results});
	}); 
	// res.send();
});

// Delete
app.get('/quotes/delete', (req,res) => {
	var retorno = db.collection(table).remove({_id:  mongodb.ObjectId(req.query.id)}, true);
	console.log('deletando: ' + req.query.id);
	// console.log('retorno: ' +  retorno);

	res.redirect('/quotes/list');
});



/* Coloca 1.000 documentos no banco de dados */
app.get('/quotes/filldb', (req, res) => {
	console.log('GET quotes/filldb');
	var jsonArray = [{"name":"Albert","quote":"Re-engineered exuding analyzer"},
{"name":"Robert","quote":"User-friendly 6th generation interface"},
{"name":"Aaron","quote":"Streamlined heuristic interface"},
{"name":"Jonathan","quote":"Centralized real-time productivity"},
{"name":"Roger","quote":"Cloned bandwidth-monitored time-frame"},
{"name":"Charles","quote":"Enterprise-wide value-added project"},
{"name":"Bobby","quote":"Universal real-time circuit"},
{"name":"Scott","quote":"Reactive disintermediate intranet"},
{"name":"William","quote":"Adaptive eco-centric software"},
{"name":"Scott","quote":"Horizontal static adapter"},
{"name":"Harold","quote":"Integrated reciprocal leverage"},
{"name":"Victor","quote":"Synchronised cohesive benchmark"},
{"name":"Jonathan","quote":"Self-enabling human-resource product"},
{"name":"Peter","quote":"Cloned composite portal"},
{"name":"Matthew","quote":"Cross-group static leverage"},
{"name":"Ralph","quote":"Universal client-server knowledge base"},
{"name":"Eric","quote":"Operative tangible workforce"},
{"name":"Ryan","quote":"Ameliorated 5th generation circuit"},
{"name":"Joseph","quote":"Mandatory cohesive implementation"},
{"name":"Craig","quote":"Fully-configurable regional model"},
{"name":"Aaron","quote":"Down-sized next generation concept"},
{"name":"Albert","quote":"Integrated radical strategy"},
{"name":"Arthur","quote":"Reactive asynchronous emulation"},
{"name":"John","quote":"Future-proofed dynamic utilisation"},
{"name":"Stephen","quote":"Public-key stable benchmark"},
{"name":"Larry","quote":"Devolved demand-driven success"},
{"name":"Donald","quote":"Synchronised upward-trending toolset"},
{"name":"Ralph","quote":"Programmable tangible infrastructure"},
{"name":"Frank","quote":"Quality-focused impactful complexity"},
{"name":"Daniel","quote":"Reactive attitude-oriented attitude"},
{"name":"Peter","quote":"Profound secondary productivity"},
{"name":"Lawrence","quote":"Distributed contextually-based middleware"},
{"name":"Steve","quote":"Horizontal bifurcated project"},
{"name":"Roger","quote":"Multi-tiered solution-oriented Graphical User Interface"},
{"name":"Shawn","quote":"Quality-focused bottom-line forecast"},
{"name":"Raymond","quote":"Innovative global definition"},
{"name":"Christopher","quote":"Proactive stable methodology"},
{"name":"William","quote":"Compatible foreground migration"},
{"name":"Douglas","quote":"Advanced discrete structure"},
{"name":"Eugene","quote":"Innovative analyzing project"},
{"name":"Anthony","quote":"Visionary encompassing functionalities"},
{"name":"John","quote":"Public-key optimal benchmark"},
{"name":"David","quote":"Re-contextualized bottom-line orchestration"},
{"name":"Bobby","quote":"Robust heuristic infrastructure"},
{"name":"Sean","quote":"Open-source upward-trending instruction set"},
{"name":"Alan","quote":"Synergistic analyzing productivity"},
{"name":"Kevin","quote":"Progressive 24/7 hub"},
{"name":"Carl","quote":"Configurable actuating matrix"},
{"name":"Howard","quote":"Fundamental actuating database"},
{"name":"Raymond","quote":"Grass-roots dedicated system engine"},
{"name":"William","quote":"Open-architected zero administration help-desk"},
{"name":"Samuel","quote":"Horizontal value-added emulation"},
{"name":"Louis","quote":"Advanced leading edge initiative"},
{"name":"Todd","quote":"Multi-tiered high-level project"},
{"name":"Randy","quote":"Re-engineered well-modulated standardization"},
{"name":"Harold","quote":"Diverse intermediate interface"},
{"name":"Roger","quote":"Optional exuding architecture"},
{"name":"William","quote":"Sharable discrete help-desk"},
{"name":"Antonio","quote":"Open-architected bottom-line access"},
{"name":"Michael","quote":"Organic optimizing hardware"},
{"name":"Justin","quote":"Integrated mobile success"},
{"name":"Victor","quote":"Profit-focused dedicated knowledge base"},
{"name":"Philip","quote":"Secured interactive adapter"},
{"name":"Benjamin","quote":"Synergized modular function"},
{"name":"Louis","quote":"Organized bottom-line complexity"},
{"name":"David","quote":"Secured cohesive policy"},
{"name":"Howard","quote":"Digitized uniform task-force"},
{"name":"Anthony","quote":"Fundamental actuating success"},
{"name":"Roger","quote":"Monitored zero tolerance toolset"},
{"name":"William","quote":"Ameliorated stable focus group"},
{"name":"Kenneth","quote":"Digitized asymmetric interface"},
{"name":"William","quote":"Programmable neutral neural-net"},
{"name":"Billy","quote":"Right-sized impactful task-force"},
{"name":"Howard","quote":"Reverse-engineered encompassing system engine"},
{"name":"Roy","quote":"Re-contextualized executive internet solution"},
{"name":"Bobby","quote":"Cross-group background hierarchy"},
{"name":"Michael","quote":"Multi-tiered systematic strategy"},
{"name":"Terry","quote":"Robust real-time strategy"},
{"name":"Jose","quote":"Down-sized neutral info-mediaries"},
{"name":"Mark","quote":"Stand-alone high-level policy"},
{"name":"Bobby","quote":"Profound demand-driven structure"},
{"name":"Craig","quote":"Total client-driven project"},
{"name":"James","quote":"Sharable logistical product"},
{"name":"Nicholas","quote":"Profit-focused next generation data-warehouse"},
{"name":"Joseph","quote":"Mandatory grid-enabled monitoring"},
{"name":"Jack","quote":"Mandatory coherent definition"},
{"name":"Harold","quote":"Down-sized neutral projection"},
{"name":"Jason","quote":"Synergistic fault-tolerant projection"},
{"name":"Jack","quote":"Ergonomic intangible functionalities"},
{"name":"Michael","quote":"Operative local throughput"},
{"name":"Eugene","quote":"Multi-channelled zero administration solution"},
{"name":"Douglas","quote":"Business-focused content-based infrastructure"},
{"name":"Fred","quote":"Intuitive directional core"},
{"name":"Daniel","quote":"Digitized radical groupware"},
{"name":"Todd","quote":"Focused real-time circuit"},
{"name":"Mark","quote":"Multi-tiered well-modulated moderator"},
{"name":"Douglas","quote":"Intuitive multi-tasking forecast"},
{"name":"Carlos","quote":"Implemented exuding middleware"},
{"name":"Bobby","quote":"Persistent grid-enabled middleware"},
{"name":"Sean","quote":"Down-sized intermediate installation"},
{"name":"Joe","quote":"Balanced exuding model"},
{"name":"Earl","quote":"Upgradable modular strategy"},
{"name":"Keith","quote":"Public-key systematic service-desk"},
{"name":"Bruce","quote":"Universal disintermediate attitude"},
{"name":"Mark","quote":"Cloned cohesive installation"},
{"name":"Victor","quote":"Function-based clear-thinking artificial intelligence"},
{"name":"Stephen","quote":"Inverse asymmetric matrices"},
{"name":"James","quote":"Ameliorated web-enabled core"},
{"name":"Todd","quote":"Enhanced cohesive standardization"},
{"name":"Bobby","quote":"Customizable optimizing service-desk"},
{"name":"Stephen","quote":"Expanded web-enabled internet solution"},
{"name":"Christopher","quote":"Grass-roots fault-tolerant process improvement"},
{"name":"Thomas","quote":"Optimized attitude-oriented migration"},
{"name":"Frank","quote":"Optional client-driven contingency"},
{"name":"Matthew","quote":"Grass-roots tertiary extranet"},
{"name":"Louis","quote":"Front-line web-enabled budgetary management"},
{"name":"Arthur","quote":"Face to face asynchronous functionalities"},
{"name":"Scott","quote":"Centralized 3rd generation extranet"},
{"name":"Charles","quote":"Focused discrete internet solution"},
{"name":"Jesse","quote":"Monitored value-added flexibility"},
{"name":"Richard","quote":"Customer-focused object-oriented approach"},
{"name":"Steven","quote":"Ergonomic bi-directional flexibility"},
{"name":"Sean","quote":"Cross-group didactic conglomeration"},
{"name":"Shawn","quote":"Inverse content-based system engine"},
{"name":"Ryan","quote":"Total 3rd generation secured line"},
{"name":"Jeffrey","quote":"Cloned homogeneous workforce"},
{"name":"Joshua","quote":"Versatile 24/7 hub"},
{"name":"Billy","quote":"Exclusive modular throughput"},
{"name":"Richard","quote":"Quality-focused bifurcated benchmark"},
{"name":"Daniel","quote":"Devolved local approach"},
{"name":"Phillip","quote":"Multi-layered 3rd generation strategy"},
{"name":"Kevin","quote":"Decentralized modular productivity"},
{"name":"Jose","quote":"Proactive context-sensitive architecture"},
{"name":"Roy","quote":"Fully-configurable zero defect approach"},
{"name":"Russell","quote":"Optional mission-critical instruction set"},
{"name":"Louis","quote":"Ergonomic heuristic access"},
{"name":"Joseph","quote":"Inverse full-range utilisation"},
{"name":"Benjamin","quote":"Universal user-facing adapter"},
{"name":"Richard","quote":"Optional stable software"},
{"name":"Robert","quote":"Self-enabling context-sensitive frame"},
{"name":"Victor","quote":"User-friendly 6th generation alliance"},
{"name":"Nicholas","quote":"Object-based didactic implementation"},
{"name":"Jeffrey","quote":"Stand-alone coherent migration"},
{"name":"Ryan","quote":"Devolved client-server frame"},
{"name":"William","quote":"Public-key regional analyzer"},
{"name":"Chris","quote":"Decentralized logistical complexity"},
{"name":"Todd","quote":"Extended maximized framework"},
{"name":"Philip","quote":"Networked explicit workforce"},
{"name":"Joe","quote":"Vision-oriented mobile info-mediaries"},
{"name":"Jerry","quote":"Profit-focused 24 hour hub"},
{"name":"Stephen","quote":"Ameliorated cohesive time-frame"},
{"name":"Justin","quote":"Automated 24 hour pricing structure"},
{"name":"Ralph","quote":"Ameliorated real-time circuit"},
{"name":"Russell","quote":"Up-sized multi-tasking algorithm"},
{"name":"Craig","quote":"Open-source system-worthy superstructure"},
{"name":"Jose","quote":"Object-based tangible installation"},
{"name":"Paul","quote":"Enterprise-wide background artificial intelligence"},
{"name":"Samuel","quote":"De-engineered intangible database"},
{"name":"Robert","quote":"Robust intermediate application"},
{"name":"Shawn","quote":"Synchronised leading edge toolset"},
{"name":"Craig","quote":"Right-sized executive circuit"},
{"name":"Kenneth","quote":"Switchable 4th generation info-mediaries"},
{"name":"John","quote":"Virtual uniform encryption"},
{"name":"Roger","quote":"Profound methodical policy"},
{"name":"Ernest","quote":"Multi-tiered attitude-oriented initiative"},
{"name":"Randy","quote":"Advanced motivating database"},
{"name":"Ronald","quote":"Open-architected well-modulated migration"},
{"name":"Donald","quote":"Business-focused global paradigm"},
{"name":"Matthew","quote":"Open-source contextually-based architecture"},
{"name":"Timothy","quote":"Enterprise-wide multi-tasking throughput"},
{"name":"Douglas","quote":"Reduced zero administration extranet"},
{"name":"Russell","quote":"Implemented client-driven artificial intelligence"},
{"name":"Thomas","quote":"Operative composite throughput"},
{"name":"Louis","quote":"Adaptive explicit contingency"},
{"name":"Keith","quote":"Re-engineered neutral capacity"},
{"name":"Jack","quote":"Public-key dedicated throughput"},
{"name":"Gregory","quote":"Enhanced bandwidth-monitored protocol"},
{"name":"Jonathan","quote":"Profit-focused foreground capability"},
{"name":"Steven","quote":"Reverse-engineered high-level concept"},
{"name":"Nicholas","quote":"Phased national protocol"},
{"name":"Eugene","quote":"Advanced empowering flexibility"},
{"name":"Victor","quote":"Proactive web-enabled synergy"},
{"name":"Jonathan","quote":"Visionary bandwidth-monitored support"},
{"name":"Billy","quote":"Open-architected eco-centric policy"},
{"name":"Arthur","quote":"Compatible neutral task-force"},
{"name":"Edward","quote":"Profit-focused even-keeled budgetary management"},
{"name":"Keith","quote":"Operative disintermediate support"},
{"name":"Terry","quote":"Quality-focused modular support"},
{"name":"Juan","quote":"Visionary intermediate matrix"},
{"name":"Alan","quote":"Pre-emptive context-sensitive leverage"},
{"name":"Joe","quote":"Inverse fresh-thinking hierarchy"},
{"name":"Philip","quote":"Multi-tiered coherent framework"},
{"name":"Louis","quote":"Multi-lateral 3rd generation moderator"},
{"name":"Antonio","quote":"Quality-focused scalable toolset"},
{"name":"Juan","quote":"Intuitive neutral conglomeration"},
{"name":"Robert","quote":"Secured actuating hierarchy"},
{"name":"Keith","quote":"Quality-focused national website"},
{"name":"John","quote":"Balanced empowering hierarchy"},
{"name":"Harold","quote":"Quality-focused optimizing intranet"},
{"name":"Keith","quote":"Re-engineered zero tolerance alliance"},
{"name":"Nicholas","quote":"Reverse-engineered intermediate system engine"},
{"name":"Philip","quote":"Fundamental needs-based service-desk"},
{"name":"Anthony","quote":"Upgradable scalable database"},
{"name":"Steve","quote":"Centralized zero defect toolset"},
{"name":"Victor","quote":"Vision-oriented homogeneous hub"},
{"name":"Benjamin","quote":"Profound fresh-thinking circuit"},
{"name":"Joe","quote":"Centralized human-resource utilisation"},
{"name":"Eric","quote":"Versatile static extranet"},
{"name":"Louis","quote":"Persistent exuding secured line"},
{"name":"Eric","quote":"Cross-group user-facing methodology"},
{"name":"Anthony","quote":"Compatible real-time capability"},
{"name":"Bruce","quote":"Quality-focused analyzing budgetary management"},
{"name":"Kenneth","quote":"Programmable neutral alliance"},
{"name":"Jack","quote":"Re-engineered explicit knowledge user"},
{"name":"Antonio","quote":"Ameliorated value-added service-desk"},
{"name":"Mark","quote":"Progressive zero administration projection"},
{"name":"Shawn","quote":"Innovative uniform challenge"},
{"name":"Andrew","quote":"Compatible stable pricing structure"},
{"name":"Harry","quote":"Quality-focused maximized firmware"},
{"name":"Frank","quote":"Devolved grid-enabled database"},
{"name":"Jimmy","quote":"Persistent content-based middleware"},
{"name":"Christopher","quote":"Organic mobile success"},
{"name":"Arthur","quote":"Virtual dedicated circuit"},
{"name":"William","quote":"Enhanced tangible website"},
{"name":"Jeffrey","quote":"Centralized content-based internet solution"},
{"name":"Sean","quote":"De-engineered 4th generation Graphic Interface"},
{"name":"Chris","quote":"Operative uniform secured line"},
{"name":"Timothy","quote":"Open-source systemic Graphical User Interface"},
{"name":"Adam","quote":"Profound web-enabled portal"},
{"name":"Stephen","quote":"Integrated scalable structure"},
{"name":"Jason","quote":"Exclusive exuding productivity"},
{"name":"Henry","quote":"Vision-oriented web-enabled emulation"},
{"name":"Ralph","quote":"Robust static customer loyalty"},
{"name":"Steven","quote":"Future-proofed systemic standardization"},
{"name":"Louis","quote":"Networked logistical analyzer"},
{"name":"Ronald","quote":"Re-contextualized mission-critical firmware"},
{"name":"Daniel","quote":"Optimized solution-oriented internet solution"},
{"name":"John","quote":"Profit-focused content-based budgetary management"},
{"name":"Alan","quote":"Versatile maximized intranet"},
{"name":"Gary","quote":"Focused intangible circuit"},
{"name":"Larry","quote":"Self-enabling asymmetric matrices"},
{"name":"Thomas","quote":"Synchronised asymmetric hub"},
{"name":"Harry","quote":"Object-based radical analyzer"},
{"name":"David","quote":"Ergonomic mission-critical open architecture"},
{"name":"Wayne","quote":"Optional object-oriented productivity"},
{"name":"Phillip","quote":"Object-based empowering policy"},
{"name":"Edward","quote":"Upgradable web-enabled architecture"},
{"name":"Shawn","quote":"Open-architected hybrid groupware"},
{"name":"Albert","quote":"Customizable impactful access"},
{"name":"Ralph","quote":"Team-oriented full-range solution"},
{"name":"Christopher","quote":"Reactive zero tolerance emulation"},
{"name":"Jose","quote":"Phased grid-enabled ability"},
{"name":"Larry","quote":"Multi-tiered next generation help-desk"},
{"name":"Kenneth","quote":"Customer-focused 3rd generation hierarchy"},
{"name":"Charles","quote":"Vision-oriented context-sensitive middleware"},
{"name":"Eugene","quote":"Function-based intermediate challenge"},
{"name":"Henry","quote":"Organic eco-centric project"},
{"name":"Ralph","quote":"Face to face regional throughput"},
{"name":"William","quote":"Configurable uniform capacity"},
{"name":"Raymond","quote":"De-engineered disintermediate open architecture"},
{"name":"Victor","quote":"Centralized global internet solution"},
{"name":"Alan","quote":"De-engineered upward-trending parallelism"},
{"name":"Eugene","quote":"Organized systemic knowledge base"},
{"name":"Clarence","quote":"Virtual human-resource interface"},
{"name":"Mark","quote":"Self-enabling upward-trending attitude"},
{"name":"Roger","quote":"Seamless system-worthy Graphic Interface"},
{"name":"Henry","quote":"Networked context-sensitive hub"},
{"name":"Jose","quote":"Vision-oriented 24 hour forecast"},
{"name":"Steve","quote":"Up-sized empowering groupware"},
{"name":"Henry","quote":"Secured disintermediate structure"},
{"name":"Jesse","quote":"Programmable multi-tasking intranet"},
{"name":"Benjamin","quote":"Focused incremental service-desk"},
{"name":"Robert","quote":"Innovative asymmetric collaboration"},
{"name":"Louis","quote":"Implemented homogeneous capacity"},
{"name":"Howard","quote":"Team-oriented non-volatile architecture"},
{"name":"Martin","quote":"User-centric system-worthy toolset"},
{"name":"Alan","quote":"Optimized solution-oriented synergy"},
{"name":"Alan","quote":"Organized reciprocal flexibility"},
{"name":"Johnny","quote":"Self-enabling upward-trending challenge"},
{"name":"Gregory","quote":"Face to face background encryption"},
{"name":"Lawrence","quote":"Robust analyzing challenge"},
{"name":"Steven","quote":"Integrated mobile architecture"},
{"name":"Jeremy","quote":"Customer-focused tertiary function"},
{"name":"Nicholas","quote":"Decentralized disintermediate application"},
{"name":"Eric","quote":"Triple-buffered heuristic project"},
{"name":"Carl","quote":"Optimized disintermediate migration"},
{"name":"Henry","quote":"Profound fault-tolerant flexibility"},
{"name":"Peter","quote":"Networked demand-driven monitoring"},
{"name":"Raymond","quote":"Proactive content-based firmware"},
{"name":"Brandon","quote":"Synergistic asymmetric leverage"},
{"name":"Russell","quote":"Cloned attitude-oriented concept"},
{"name":"Todd","quote":"Innovative systemic moderator"},
{"name":"Edward","quote":"Vision-oriented didactic approach"},
{"name":"Clarence","quote":"Cross-platform background success"},
{"name":"Wayne","quote":"Realigned logistical capacity"},
{"name":"Steven","quote":"Optional context-sensitive policy"},
{"name":"Jonathan","quote":"Ameliorated solution-oriented info-mediaries"},
{"name":"Bruce","quote":"Fundamental coherent help-desk"},
{"name":"Ryan","quote":"Customer-focused reciprocal access"},
{"name":"Jerry","quote":"Team-oriented explicit matrix"},
{"name":"Jerry","quote":"User-friendly disintermediate info-mediaries"},
{"name":"Aaron","quote":"De-engineered systemic contingency"},
{"name":"Justin","quote":"Synergistic local local area network"},
{"name":"Antonio","quote":"Fully-configurable optimal capacity"},
{"name":"Joshua","quote":"Future-proofed explicit knowledge base"},
{"name":"Joe","quote":"Fundamental zero defect migration"},
{"name":"Howard","quote":"Innovative full-range interface"},
{"name":"Mark","quote":"Sharable multi-state customer loyalty"},
{"name":"Larry","quote":"Decentralized well-modulated internet solution"},
{"name":"Walter","quote":"Programmable value-added algorithm"},
{"name":"Benjamin","quote":"Face to face bi-directional website"},
{"name":"Jose","quote":"Reverse-engineered didactic help-desk"},
{"name":"Joseph","quote":"Front-line 4th generation installation"},
{"name":"Steven","quote":"Re-engineered value-added attitude"},
{"name":"Roger","quote":"Expanded bi-directional hierarchy"},
{"name":"Harry","quote":"Robust optimizing orchestration"},
{"name":"Daniel","quote":"Robust optimal core"},
{"name":"Andrew","quote":"Reactive dynamic intranet"},
{"name":"Timothy","quote":"Open-architected executive focus group"},
{"name":"Adam","quote":"Future-proofed neutral infrastructure"},
{"name":"Philip","quote":"Phased object-oriented workforce"},
{"name":"Ernest","quote":"Multi-tiered upward-trending archive"},
{"name":"Anthony","quote":"Fundamental global website"},
{"name":"Earl","quote":"Optimized 3rd generation matrices"},
{"name":"Ryan","quote":"Public-key attitude-oriented middleware"},
{"name":"Jerry","quote":"Intuitive client-driven algorithm"},
{"name":"Harold","quote":"Profit-focused incremental pricing structure"},
{"name":"Clarence","quote":"Centralized global encoding"},
{"name":"Joseph","quote":"Profound human-resource architecture"},
{"name":"Raymond","quote":"Enterprise-wide value-added complexity"},
{"name":"Roy","quote":"Ameliorated global task-force"},
{"name":"Jonathan","quote":"Reduced cohesive middleware"},
{"name":"Eric","quote":"Function-based heuristic initiative"},
{"name":"Steve","quote":"Intuitive uniform utilisation"},
{"name":"David","quote":"Reverse-engineered stable leverage"},
{"name":"Thomas","quote":"Universal context-sensitive capability"},
{"name":"Henry","quote":"Innovative actuating workforce"},
{"name":"Willie","quote":"Proactive 6th generation access"},
{"name":"Stephen","quote":"Polarised actuating standardization"},
{"name":"Henry","quote":"Centralized needs-based access"},
{"name":"Ralph","quote":"Ameliorated multi-tasking open system"},
{"name":"Ralph","quote":"Customizable analyzing paradigm"},
{"name":"Patrick","quote":"Implemented bandwidth-monitored matrices"},
{"name":"Joshua","quote":"Extended disintermediate hardware"},
{"name":"Matthew","quote":"Intuitive local hardware"},
{"name":"Lawrence","quote":"Open-architected needs-based data-warehouse"},
{"name":"Martin","quote":"Innovative zero defect interface"},
{"name":"Douglas","quote":"Intuitive systemic instruction set"},
{"name":"Steve","quote":"Cross-platform dedicated paradigm"},
{"name":"Henry","quote":"Universal holistic concept"},
{"name":"Juan","quote":"Multi-tiered maximized framework"},
{"name":"Willie","quote":"Extended bi-directional model"},
{"name":"Kevin","quote":"Exclusive bottom-line capacity"},
{"name":"Ronald","quote":"Pre-emptive disintermediate moderator"},
{"name":"Steven","quote":"Open-architected context-sensitive analyzer"},
{"name":"Eric","quote":"Virtual bifurcated architecture"},
{"name":"Thomas","quote":"Total secondary concept"},
{"name":"Paul","quote":"Cross-platform interactive product"},
{"name":"Joshua","quote":"Vision-oriented responsive open architecture"},
{"name":"Victor","quote":"Quality-focused homogeneous instruction set"},
{"name":"Charles","quote":"Seamless 24/7 orchestration"},
{"name":"Gregory","quote":"Profit-focused human-resource methodology"},
{"name":"Chris","quote":"Realigned solution-oriented project"},
{"name":"Russell","quote":"Networked background encoding"},
{"name":"Carlos","quote":"De-engineered 3rd generation policy"},
{"name":"Jason","quote":"Intuitive zero defect parallelism"},
{"name":"Terry","quote":"Right-sized cohesive instruction set"},
{"name":"Patrick","quote":"Realigned tangible model"},
{"name":"Wayne","quote":"Open-source attitude-oriented knowledge base"},
{"name":"John","quote":"Reverse-engineered multi-state throughput"},
{"name":"David","quote":"Front-line intermediate throughput"},
{"name":"Matthew","quote":"Phased multi-tasking superstructure"},
{"name":"Keith","quote":"Reactive discrete core"},
{"name":"Ryan","quote":"Open-source multi-state toolset"},
{"name":"Jimmy","quote":"Team-oriented asymmetric application"},
{"name":"Michael","quote":"Assimilated zero administration installation"},
{"name":"John","quote":"Devolved zero administration success"},
{"name":"Nicholas","quote":"Distributed disintermediate model"},
{"name":"Ralph","quote":"Ergonomic empowering project"},
{"name":"Jeremy","quote":"Balanced global extranet"},
{"name":"Gary","quote":"Multi-lateral web-enabled software"},
{"name":"Todd","quote":"Inverse maximized functionalities"},
{"name":"Phillip","quote":"Synergized systematic throughput"},
{"name":"Louis","quote":"Reactive 4th generation time-frame"},
{"name":"Timothy","quote":"Ergonomic homogeneous firmware"},
{"name":"Larry","quote":"Multi-channelled 5th generation framework"},
{"name":"Carl","quote":"Progressive secondary collaboration"},
{"name":"Carl","quote":"Fundamental tangible local area network"},
{"name":"Ryan","quote":"Innovative maximized ability"},
{"name":"Lawrence","quote":"Secured explicit extranet"},
{"name":"Carl","quote":"Sharable explicit moderator"},
{"name":"Roger","quote":"Ergonomic 5th generation success"},
{"name":"Douglas","quote":"Integrated 24/7 frame"},
{"name":"Thomas","quote":"Automated interactive Graphic Interface"},
{"name":"Philip","quote":"Down-sized client-server toolset"},
{"name":"Russell","quote":"Reduced dynamic paradigm"},
{"name":"Kevin","quote":"Re-contextualized grid-enabled matrix"},
{"name":"Michael","quote":"Automated cohesive conglomeration"},
{"name":"Roger","quote":"Implemented cohesive interface"},
{"name":"Mark","quote":"Polarised scalable local area network"},
{"name":"Craig","quote":"Phased homogeneous service-desk"},
{"name":"Harold","quote":"Multi-channelled 4th generation algorithm"},
{"name":"Chris","quote":"Versatile holistic implementation"},
{"name":"Christopher","quote":"Assimilated optimizing success"},
{"name":"Stephen","quote":"Multi-layered optimal process improvement"},
{"name":"Nicholas","quote":"Centralized bandwidth-monitored synergy"},
{"name":"Bruce","quote":"Virtual radical model"},
{"name":"Jack","quote":"Reduced regional implementation"},
{"name":"Albert","quote":"Enhanced multi-tasking flexibility"},
{"name":"Mark","quote":"Multi-lateral 24 hour budgetary management"},
{"name":"Shawn","quote":"Focused uniform collaboration"},
{"name":"Matthew","quote":"Business-focused interactive knowledge base"},
{"name":"Donald","quote":"Upgradable systematic frame"},
{"name":"Ralph","quote":"Pre-emptive incremental intranet"},
{"name":"Terry","quote":"Profit-focused transitional focus group"},
{"name":"David","quote":"Fundamental interactive process improvement"},
{"name":"Steve","quote":"Synchronised heuristic analyzer"},
{"name":"Kevin","quote":"Face to face object-oriented Graphical User Interface"},
{"name":"Charles","quote":"Assimilated dedicated concept"},
{"name":"Aaron","quote":"Face to face solution-oriented workforce"},
{"name":"Jack","quote":"Optional multi-tasking paradigm"},
{"name":"Alan","quote":"Triple-buffered high-level middleware"},
{"name":"James","quote":"Business-focused incremental encryption"},
{"name":"Roger","quote":"Customer-focused solution-oriented Graphic Interface"},
{"name":"Roger","quote":"Multi-layered real-time ability"},
{"name":"Harry","quote":"Re-engineered logistical firmware"},
{"name":"Todd","quote":"Robust leading edge workforce"},
{"name":"Louis","quote":"Cloned cohesive middleware"},
{"name":"Arthur","quote":"Exclusive secondary core"},
{"name":"Johnny","quote":"User-friendly incremental secured line"},
{"name":"Frank","quote":"Profit-focused methodical productivity"},
{"name":"Douglas","quote":"Synergistic 3rd generation support"},
{"name":"Chris","quote":"Compatible asymmetric installation"},
{"name":"William","quote":"Cloned hybrid architecture"},
{"name":"Matthew","quote":"Monitored multi-tasking project"},
{"name":"Matthew","quote":"Re-engineered content-based local area network"},
{"name":"Dennis","quote":"Advanced bandwidth-monitored monitoring"},
{"name":"George","quote":"Organized directional conglomeration"},
{"name":"Joshua","quote":"Innovative incremental open system"},
{"name":"Aaron","quote":"Up-sized global application"},
{"name":"Jerry","quote":"Fundamental impactful pricing structure"},
{"name":"Jeremy","quote":"Reactive maximized infrastructure"},
{"name":"Henry","quote":"Profound transitional capacity"},
{"name":"Shawn","quote":"Pre-emptive systemic pricing structure"},
{"name":"James","quote":"Proactive empowering superstructure"},
{"name":"Jesse","quote":"Face to face 24/7 alliance"},
{"name":"Steven","quote":"Horizontal background analyzer"},
{"name":"Louis","quote":"Down-sized dedicated initiative"},
{"name":"Bruce","quote":"Multi-layered regional collaboration"},
{"name":"Harold","quote":"Configurable disintermediate firmware"},
{"name":"Adam","quote":"Pre-emptive 24/7 paradigm"},
{"name":"Larry","quote":"Profound demand-driven strategy"},
{"name":"Randy","quote":"Advanced didactic capacity"},
{"name":"Nicholas","quote":"Profound content-based toolset"},
{"name":"Jason","quote":"Object-based bifurcated orchestration"},
{"name":"Howard","quote":"Object-based zero administration core"},
{"name":"Matthew","quote":"Mandatory cohesive pricing structure"},
{"name":"Juan","quote":"Triple-buffered 4th generation implementation"},
{"name":"William","quote":"Universal mission-critical initiative"},
{"name":"Matthew","quote":"Ergonomic well-modulated alliance"},
{"name":"Jesse","quote":"Devolved clear-thinking definition"},
{"name":"Carlos","quote":"Distributed contextually-based support"},
{"name":"Todd","quote":"Reactive client-server info-mediaries"},
{"name":"Bruce","quote":"Proactive value-added function"},
{"name":"Nicholas","quote":"Optional user-facing orchestration"},
{"name":"Jason","quote":"Assimilated systematic instruction set"},
{"name":"Aaron","quote":"Function-based bandwidth-monitored info-mediaries"},
{"name":"Wayne","quote":"Function-based next generation concept"},
{"name":"Jesse","quote":"Networked scalable portal"},
{"name":"Jeremy","quote":"Total homogeneous local area network"},
{"name":"Carlos","quote":"Public-key user-facing encoding"},
{"name":"Earl","quote":"Cloned human-resource productivity"},
{"name":"Steven","quote":"Upgradable exuding standardization"},
{"name":"Harry","quote":"Organic context-sensitive instruction set"},
{"name":"Albert","quote":"Reduced actuating Graphical User Interface"},
{"name":"Henry","quote":"Triple-buffered dynamic groupware"},
{"name":"Juan","quote":"Persistent homogeneous budgetary management"},
{"name":"Paul","quote":"Optimized analyzing support"},
{"name":"Arthur","quote":"Diverse object-oriented knowledge base"},
{"name":"Bobby","quote":"Realigned context-sensitive alliance"},
{"name":"Scott","quote":"Cross-group zero administration focus group"},
{"name":"Johnny","quote":"Switchable 24/7 capacity"},
{"name":"Walter","quote":"Stand-alone analyzing instruction set"},
{"name":"Christopher","quote":"Decentralized impactful adapter"},
{"name":"Todd","quote":"Polarised explicit encoding"},
{"name":"Steve","quote":"User-friendly zero administration hierarchy"},
{"name":"Joe","quote":"Self-enabling attitude-oriented software"},
{"name":"Frank","quote":"Re-contextualized asynchronous encoding"},
{"name":"Joshua","quote":"Robust 24 hour methodology"},
{"name":"Raymond","quote":"Multi-layered grid-enabled initiative"},
{"name":"Raymond","quote":"Enhanced tertiary software"},
{"name":"Roy","quote":"Right-sized didactic solution"},
{"name":"Gary","quote":"Organized high-level contingency"},
{"name":"Ryan","quote":"Synergized value-added groupware"},
{"name":"Joe","quote":"Upgradable object-oriented standardization"},
{"name":"Kenneth","quote":"Operative static benchmark"},
{"name":"Nicholas","quote":"Multi-tiered encompassing throughput"},
{"name":"Jimmy","quote":"Assimilated solution-oriented neural-net"},
{"name":"Harold","quote":"Cloned contextually-based extranet"},
{"name":"Paul","quote":"Switchable solution-oriented groupware"},
{"name":"Willie","quote":"Multi-tiered impactful time-frame"},
{"name":"Joe","quote":"Seamless responsive adapter"},
{"name":"Adam","quote":"Expanded holistic protocol"},
{"name":"Chris","quote":"Networked eco-centric synergy"},
{"name":"Steve","quote":"Synergistic real-time matrices"},
{"name":"Steve","quote":"Universal intermediate algorithm"},
{"name":"Robert","quote":"Profound transitional middleware"},
{"name":"Victor","quote":"Streamlined 24 hour pricing structure"},
{"name":"Ernest","quote":"Virtual intangible Graphical User Interface"},
{"name":"Stephen","quote":"Multi-tiered mission-critical emulation"},
{"name":"Clarence","quote":"Public-key 5th generation circuit"},
{"name":"Russell","quote":"Secured asymmetric migration"},
{"name":"Patrick","quote":"Configurable zero tolerance capability"},
{"name":"Carlos","quote":"Balanced bi-directional ability"},
{"name":"Frank","quote":"Enterprise-wide human-resource paradigm"},
{"name":"Fred","quote":"Triple-buffered 24/7 superstructure"},
{"name":"Sean","quote":"Profit-focused uniform utilisation"},
{"name":"Matthew","quote":"Adaptive non-volatile solution"},
{"name":"Martin","quote":"Multi-channelled even-keeled installation"},
{"name":"Richard","quote":"Customer-focused encompassing installation"},
{"name":"George","quote":"Virtual logistical synergy"},
{"name":"Terry","quote":"Face to face directional complexity"},
{"name":"Bruce","quote":"Distributed contextually-based paradigm"},
{"name":"Louis","quote":"Automated web-enabled strategy"},
{"name":"Antonio","quote":"Secured mobile migration"},
{"name":"Billy","quote":"Upgradable secondary data-warehouse"},
{"name":"Brian","quote":"Operative executive info-mediaries"},
{"name":"Carl","quote":"Decentralized next generation solution"},
{"name":"Matthew","quote":"De-engineered asymmetric paradigm"},
{"name":"Carl","quote":"Devolved user-facing software"},
{"name":"James","quote":"Ergonomic radical open system"},
{"name":"Clarence","quote":"Multi-tiered 4th generation forecast"},
{"name":"Alan","quote":"Down-sized next generation Graphical User Interface"},
{"name":"Steven","quote":"Function-based modular protocol"},
{"name":"Donald","quote":"Configurable incremental pricing structure"},
{"name":"Clarence","quote":"Networked composite concept"},
{"name":"Michael","quote":"Open-architected upward-trending utilisation"},
{"name":"Larry","quote":"Stand-alone full-range analyzer"},
{"name":"Kevin","quote":"Versatile directional complexity"},
{"name":"Todd","quote":"Mandatory tangible matrices"},
{"name":"Michael","quote":"Cross-platform tangible monitoring"},
{"name":"Louis","quote":"Persistent 3rd generation core"},
{"name":"Peter","quote":"Networked well-modulated emulation"},
{"name":"David","quote":"User-friendly regional success"},
{"name":"Louis","quote":"Right-sized client-driven parallelism"},
{"name":"Jeffrey","quote":"Advanced maximized implementation"},
{"name":"Carlos","quote":"Assimilated modular access"},
{"name":"Timothy","quote":"Function-based asynchronous project"},
{"name":"Raymond","quote":"Inverse grid-enabled implementation"},
{"name":"Brian","quote":"Ergonomic zero defect task-force"},
{"name":"Justin","quote":"Customer-focused discrete infrastructure"},
{"name":"Alan","quote":"Horizontal even-keeled approach"},
{"name":"Fred","quote":"Operative 3rd generation policy"},
{"name":"Charles","quote":"Decentralized real-time initiative"},
{"name":"Walter","quote":"Public-key 24/7 throughput"},
{"name":"Henry","quote":"Synchronised demand-driven firmware"},
{"name":"Ronald","quote":"Optimized coherent neural-net"},
{"name":"Brian","quote":"Synergized fresh-thinking concept"},
{"name":"Alan","quote":"Right-sized non-volatile projection"},
{"name":"Alan","quote":"Triple-buffered human-resource process improvement"},
{"name":"William","quote":"Polarised fault-tolerant moratorium"},
{"name":"Paul","quote":"Grass-roots static focus group"},
{"name":"Kenneth","quote":"Right-sized solution-oriented functionalities"},
{"name":"Paul","quote":"Total motivating parallelism"},
{"name":"Victor","quote":"Distributed stable encryption"},
{"name":"Carl","quote":"Reactive zero defect synergy"},
{"name":"Joe","quote":"Object-based encompassing collaboration"},
{"name":"Anthony","quote":"Balanced transitional moratorium"},
{"name":"Juan","quote":"Automated eco-centric implementation"},
{"name":"Johnny","quote":"Up-sized discrete middleware"},
{"name":"Jerry","quote":"User-friendly object-oriented access"},
{"name":"Eugene","quote":"Switchable national challenge"},
{"name":"Jason","quote":"Synergized directional flexibility"},
{"name":"Billy","quote":"Monitored executive paradigm"},
{"name":"Ronald","quote":"Horizontal needs-based attitude"},
{"name":"Robert","quote":"Public-key zero administration core"},
{"name":"Thomas","quote":"Object-based heuristic algorithm"},
{"name":"Benjamin","quote":"Quality-focused foreground application"},
{"name":"Scott","quote":"Intuitive scalable website"},
{"name":"Phillip","quote":"De-engineered bandwidth-monitored open system"},
{"name":"Mark","quote":"Reduced grid-enabled access"},
{"name":"Brandon","quote":"Secured background help-desk"},
{"name":"Brandon","quote":"Multi-lateral 3rd generation success"},
{"name":"Frank","quote":"Cross-group executive array"},
{"name":"Kenneth","quote":"Devolved mission-critical policy"},
{"name":"Thomas","quote":"Cross-group interactive hub"},
{"name":"Todd","quote":"Grass-roots 6th generation conglomeration"},
{"name":"Jonathan","quote":"De-engineered needs-based success"},
{"name":"Charles","quote":"Ameliorated mission-critical moratorium"},
{"name":"Juan","quote":"Public-key asymmetric contingency"},
{"name":"Randy","quote":"Streamlined bifurcated collaboration"},
{"name":"Johnny","quote":"Streamlined transitional infrastructure"},
{"name":"John","quote":"Face to face methodical core"},
{"name":"Christopher","quote":"Decentralized 3rd generation functionalities"},
{"name":"John","quote":"Open-architected optimizing moderator"},
{"name":"Harold","quote":"Virtual human-resource architecture"},
{"name":"Ryan","quote":"Operative object-oriented knowledge base"},
{"name":"Larry","quote":"Cross-platform hybrid intranet"},
{"name":"William","quote":"Future-proofed solution-oriented analyzer"},
{"name":"Carlos","quote":"De-engineered uniform product"},
{"name":"Jeremy","quote":"Streamlined zero defect installation"},
{"name":"Wayne","quote":"Triple-buffered multi-state artificial intelligence"},
{"name":"Daniel","quote":"Multi-tiered zero tolerance emulation"},
{"name":"Antonio","quote":"User-friendly high-level budgetary management"},
{"name":"Jason","quote":"Exclusive 6th generation algorithm"},
{"name":"Johnny","quote":"Realigned bi-directional productivity"},
{"name":"Donald","quote":"Assimilated impactful adapter"},
{"name":"Walter","quote":"Networked even-keeled paradigm"},
{"name":"Jerry","quote":"Exclusive zero administration service-desk"},
{"name":"Douglas","quote":"Programmable intangible conglomeration"},
{"name":"Kevin","quote":"Streamlined optimizing Graphical User Interface"},
{"name":"Daniel","quote":"Re-engineered actuating intranet"},
{"name":"Gary","quote":"Multi-tiered holistic superstructure"},
{"name":"William","quote":"Multi-lateral upward-trending data-warehouse"},
{"name":"Antonio","quote":"Profound optimizing adapter"},
{"name":"Steven","quote":"Exclusive 4th generation function"},
{"name":"Keith","quote":"Realigned 24 hour system engine"},
{"name":"Jeremy","quote":"Upgradable zero administration superstructure"},
{"name":"Jesse","quote":"Multi-lateral directional software"},
{"name":"Raymond","quote":"Grass-roots hybrid project"},
{"name":"Christopher","quote":"Innovative disintermediate website"},
{"name":"Kenneth","quote":"Configurable global collaboration"},
{"name":"Alan","quote":"Devolved solution-oriented methodology"},
{"name":"Adam","quote":"Optimized neutral flexibility"},
{"name":"Eugene","quote":"Grass-roots composite task-force"},
{"name":"Clarence","quote":"Re-contextualized context-sensitive adapter"},
{"name":"Samuel","quote":"Reverse-engineered zero defect knowledge base"},
{"name":"Jesse","quote":"Synchronised needs-based encryption"},
{"name":"Brandon","quote":"Automated next generation parallelism"},
{"name":"Jose","quote":"Expanded 24/7 productivity"},
{"name":"Ralph","quote":"Advanced static support"},
{"name":"Bobby","quote":"Reduced national capability"},
{"name":"Fred","quote":"Switchable tertiary framework"},
{"name":"Willie","quote":"Multi-channelled modular interface"},
{"name":"Wayne","quote":"Grass-roots executive contingency"},
{"name":"Raymond","quote":"Synergistic needs-based forecast"},
{"name":"Todd","quote":"Re-engineered asynchronous project"},
{"name":"Roy","quote":"Operative homogeneous orchestration"},
{"name":"Albert","quote":"Reduced actuating open system"},
{"name":"Lawrence","quote":"Public-key content-based hierarchy"},
{"name":"Eric","quote":"User-friendly upward-trending customer loyalty"},
{"name":"Michael","quote":"Universal uniform secured line"},
{"name":"Russell","quote":"Up-sized regional architecture"},
{"name":"Bruce","quote":"User-centric global system engine"},
{"name":"Frank","quote":"Upgradable motivating encryption"},
{"name":"Randy","quote":"Persevering executive capability"},
{"name":"Jeffrey","quote":"Devolved content-based data-warehouse"},
{"name":"Jason","quote":"De-engineered national hierarchy"},
{"name":"Daniel","quote":"Vision-oriented asymmetric structure"},
{"name":"Joe","quote":"Organic bifurcated migration"},
{"name":"Henry","quote":"Cross-group demand-driven array"},
{"name":"Wayne","quote":"Expanded reciprocal forecast"},
{"name":"Peter","quote":"Cross-platform client-driven concept"},
{"name":"Mark","quote":"Future-proofed mobile middleware"},
{"name":"Christopher","quote":"Open-source systemic capacity"},
{"name":"Willie","quote":"Advanced secondary service-desk"},
{"name":"Aaron","quote":"Visionary heuristic firmware"},
{"name":"Justin","quote":"Intuitive coherent implementation"},
{"name":"Antonio","quote":"Monitored incremental ability"},
{"name":"Joseph","quote":"Innovative homogeneous database"},
{"name":"Richard","quote":"Object-based holistic algorithm"},
{"name":"Jerry","quote":"Proactive homogeneous throughput"},
{"name":"Albert","quote":"Enterprise-wide non-volatile paradigm"},
{"name":"Roy","quote":"Organized 4th generation moderator"},
{"name":"Arthur","quote":"Virtual background adapter"},
{"name":"Jack","quote":"Robust even-keeled extranet"},
{"name":"Russell","quote":"Re-contextualized even-keeled projection"},
{"name":"Anthony","quote":"Total heuristic architecture"},
{"name":"Raymond","quote":"Stand-alone regional emulation"},
{"name":"Joshua","quote":"Customer-focused contextually-based knowledge base"},
{"name":"Phillip","quote":"Stand-alone executive access"},
{"name":"Richard","quote":"Robust executive extranet"},
{"name":"Arthur","quote":"Phased systemic hub"},
{"name":"Sean","quote":"Future-proofed actuating internet solution"},
{"name":"Brian","quote":"Vision-oriented 4th generation database"},
{"name":"Brian","quote":"Up-sized local core"},
{"name":"Walter","quote":"Distributed bifurcated interface"},
{"name":"Justin","quote":"Reactive composite framework"},
{"name":"Raymond","quote":"Ergonomic mobile task-force"},
{"name":"Raymond","quote":"Customizable bottom-line functionalities"},
{"name":"Ralph","quote":"Ergonomic user-facing alliance"},
{"name":"Ralph","quote":"Self-enabling interactive open architecture"},
{"name":"Kenneth","quote":"Multi-layered asynchronous project"},
{"name":"James","quote":"Versatile uniform database"},
{"name":"Edward","quote":"Open-architected 6th generation access"},
{"name":"Bruce","quote":"Optional real-time extranet"},
{"name":"Clarence","quote":"Virtual attitude-oriented productivity"},
{"name":"Jason","quote":"Operative 24/7 extranet"},
{"name":"Lawrence","quote":"Down-sized stable synergy"},
{"name":"Charles","quote":"Cloned client-server paradigm"},
{"name":"Harry","quote":"Enterprise-wide optimal middleware"},
{"name":"Michael","quote":"Progressive value-added capability"},
{"name":"Donald","quote":"Fundamental asymmetric alliance"},
{"name":"Shawn","quote":"Advanced interactive concept"},
{"name":"David","quote":"Re-contextualized fresh-thinking parallelism"},
{"name":"Bruce","quote":"Grass-roots hybrid artificial intelligence"},
{"name":"Clarence","quote":"Function-based 6th generation protocol"},
{"name":"Mark","quote":"Configurable optimal workforce"},
{"name":"Kevin","quote":"Organic client-server productivity"},
{"name":"Jason","quote":"Horizontal systemic benchmark"},
{"name":"Bobby","quote":"Digitized interactive matrix"},
{"name":"Steven","quote":"Fundamental 5th generation matrices"},
{"name":"Robert","quote":"User-centric contextually-based benchmark"},
{"name":"Kevin","quote":"Networked hybrid hardware"},
{"name":"Peter","quote":"Assimilated encompassing monitoring"},
{"name":"Joe","quote":"Quality-focused user-facing encryption"},
{"name":"Richard","quote":"Synergized human-resource policy"},
{"name":"Andrew","quote":"Ergonomic foreground orchestration"},
{"name":"Roger","quote":"Extended coherent complexity"},
{"name":"Shawn","quote":"Devolved intermediate knowledge user"},
{"name":"Daniel","quote":"Multi-channelled exuding implementation"},
{"name":"Willie","quote":"Optimized next generation info-mediaries"},
{"name":"Harold","quote":"Exclusive motivating standardization"},
{"name":"Jose","quote":"User-centric value-added firmware"},
{"name":"Harry","quote":"Multi-lateral web-enabled infrastructure"},
{"name":"Patrick","quote":"Re-engineered impactful functionalities"},
{"name":"Wayne","quote":"Down-sized regional open architecture"},
{"name":"Nicholas","quote":"Stand-alone mission-critical pricing structure"},
{"name":"Phillip","quote":"Profit-focused modular task-force"},
{"name":"Randy","quote":"Synergistic grid-enabled moratorium"},
{"name":"Johnny","quote":"Re-contextualized multimedia open system"},
{"name":"Louis","quote":"Optional homogeneous software"},
{"name":"Brian","quote":"User-friendly bandwidth-monitored Graphic Interface"},
{"name":"Eugene","quote":"Multi-channelled 24 hour knowledge user"},
{"name":"Aaron","quote":"Polarised regional time-frame"},
{"name":"Keith","quote":"Triple-buffered systematic ability"},
{"name":"Ronald","quote":"Persistent zero defect framework"},
{"name":"Adam","quote":"Visionary motivating frame"},
{"name":"Kevin","quote":"Virtual 6th generation software"},
{"name":"Edward","quote":"Diverse web-enabled knowledge base"},
{"name":"Dennis","quote":"Proactive 5th generation encryption"},
{"name":"Steve","quote":"Horizontal background matrix"},
{"name":"Nicholas","quote":"Enterprise-wide real-time superstructure"},
{"name":"Jack","quote":"Future-proofed bifurcated hardware"},
{"name":"Billy","quote":"Right-sized value-added interface"},
{"name":"Robert","quote":"Adaptive analyzing moratorium"},
{"name":"Gary","quote":"Operative analyzing workforce"},
{"name":"Ryan","quote":"Sharable holistic help-desk"},
{"name":"Wayne","quote":"Up-sized incremental challenge"},
{"name":"Daniel","quote":"Focused optimizing hub"},
{"name":"Steve","quote":"User-centric dynamic productivity"},
{"name":"Fred","quote":"Centralized responsive customer loyalty"},
{"name":"Clarence","quote":"Extended tertiary protocol"},
{"name":"Johnny","quote":"Team-oriented next generation artificial intelligence"},
{"name":"Thomas","quote":"Switchable content-based firmware"},
{"name":"Ernest","quote":"Inverse disintermediate moratorium"},
{"name":"Gary","quote":"Up-sized mobile encoding"},
{"name":"Harold","quote":"Robust secondary hierarchy"},
{"name":"Alan","quote":"Centralized full-range data-warehouse"},
{"name":"Andrew","quote":"Mandatory bandwidth-monitored benchmark"},
{"name":"Martin","quote":"Managed secondary model"},
{"name":"Jeremy","quote":"Advanced dedicated initiative"},
{"name":"Howard","quote":"Ameliorated high-level superstructure"},
{"name":"Joe","quote":"Fully-configurable zero tolerance moratorium"},
{"name":"Gary","quote":"Secured zero tolerance solution"},
{"name":"Samuel","quote":"Adaptive zero administration knowledge user"},
{"name":"William","quote":"Customer-focused zero tolerance benchmark"},
{"name":"Eric","quote":"Switchable tertiary application"},
{"name":"Gary","quote":"Distributed systematic hub"},
{"name":"Kevin","quote":"Implemented discrete frame"},
{"name":"Johnny","quote":"Balanced 24/7 analyzer"},
{"name":"Martin","quote":"Diverse full-range analyzer"},
{"name":"Johnny","quote":"Cloned tangible monitoring"},
{"name":"William","quote":"Extended eco-centric superstructure"},
{"name":"Richard","quote":"Organic even-keeled firmware"},
{"name":"Raymond","quote":"Grass-roots logistical website"},
{"name":"Daniel","quote":"Configurable modular moderator"},
{"name":"Kevin","quote":"Operative next generation hierarchy"},
{"name":"Andrew","quote":"Focused zero tolerance structure"},
{"name":"Randy","quote":"Automated intermediate conglomeration"},
{"name":"Christopher","quote":"Compatible cohesive help-desk"},
{"name":"John","quote":"Organized upward-trending parallelism"},
{"name":"Justin","quote":"Organized fault-tolerant approach"},
{"name":"Frank","quote":"Implemented composite contingency"},
{"name":"Philip","quote":"Switchable human-resource groupware"},
{"name":"Lawrence","quote":"Public-key clear-thinking budgetary management"},
{"name":"Clarence","quote":"Compatible regional pricing structure"},
{"name":"Victor","quote":"Customer-focused 24 hour frame"},
{"name":"Gerald","quote":"Cross-platform optimal utilisation"},
{"name":"Dennis","quote":"Enterprise-wide cohesive protocol"},
{"name":"Jimmy","quote":"Customer-focused well-modulated secured line"},
{"name":"Earl","quote":"Synergized tertiary pricing structure"},
{"name":"Donald","quote":"Progressive heuristic hardware"},
{"name":"Fred","quote":"Multi-channelled contextually-based collaboration"},
{"name":"Frank","quote":"Optional homogeneous strategy"},
{"name":"Roy","quote":"Customer-focused encompassing process improvement"},
{"name":"Martin","quote":"Ergonomic mobile benchmark"},
{"name":"Paul","quote":"Advanced dedicated toolset"},
{"name":"Benjamin","quote":"Self-enabling clear-thinking forecast"},
{"name":"Carl","quote":"Persistent incremental protocol"},
{"name":"Ronald","quote":"Customizable bi-directional productivity"},
{"name":"Eugene","quote":"Customizable global core"},
{"name":"Eric","quote":"Upgradable dynamic challenge"},
{"name":"Stephen","quote":"Focused high-level forecast"},
{"name":"Gerald","quote":"User-friendly responsive ability"},
{"name":"Peter","quote":"Proactive transitional analyzer"},
{"name":"Carl","quote":"Persistent zero defect process improvement"},
{"name":"Willie","quote":"Re-engineered regional core"},
{"name":"Thomas","quote":"Distributed reciprocal middleware"},
{"name":"Gerald","quote":"Mandatory object-oriented portal"},
{"name":"Gary","quote":"Decentralized multi-tasking internet solution"},
{"name":"William","quote":"Progressive systemic time-frame"},
{"name":"Keith","quote":"Cross-group zero administration initiative"},
{"name":"Todd","quote":"User-friendly exuding implementation"},
{"name":"Martin","quote":"Optional foreground open architecture"},
{"name":"Patrick","quote":"Decentralized zero tolerance help-desk"},
{"name":"Howard","quote":"Reactive reciprocal website"},
{"name":"Jose","quote":"Front-line web-enabled function"},
{"name":"Benjamin","quote":"Future-proofed non-volatile framework"},
{"name":"Charles","quote":"Profound responsive productivity"},
{"name":"Carl","quote":"Operative didactic moratorium"},
{"name":"Russell","quote":"Triple-buffered non-volatile installation"},
{"name":"Philip","quote":"Streamlined dedicated model"},
{"name":"Craig","quote":"Public-key clear-thinking utilisation"},
{"name":"Justin","quote":"Enhanced bandwidth-monitored customer loyalty"},
{"name":"Adam","quote":"Open-source intangible utilisation"},
{"name":"Kevin","quote":"Customizable intangible help-desk"},
{"name":"Ralph","quote":"Streamlined asynchronous task-force"},
{"name":"Brian","quote":"Virtual foreground success"},
{"name":"Jerry","quote":"Exclusive clear-thinking monitoring"},
{"name":"Aaron","quote":"Total multimedia encryption"},
{"name":"Roger","quote":"Proactive actuating throughput"},
{"name":"Ernest","quote":"Pre-emptive systemic open system"},
{"name":"Lawrence","quote":"Vision-oriented holistic leverage"},
{"name":"Ronald","quote":"Cross-group bottom-line algorithm"},
{"name":"Joe","quote":"Front-line discrete groupware"},
{"name":"Timothy","quote":"Compatible composite application"},
{"name":"Charles","quote":"Right-sized needs-based solution"},
{"name":"Willie","quote":"Public-key neutral capability"},
{"name":"Howard","quote":"Diverse bandwidth-monitored protocol"},
{"name":"Scott","quote":"Streamlined bottom-line analyzer"},
{"name":"Antonio","quote":"Fundamental attitude-oriented complexity"},
{"name":"Jeremy","quote":"Face to face coherent array"},
{"name":"Douglas","quote":"Sharable encompassing framework"},
{"name":"Timothy","quote":"Self-enabling attitude-oriented policy"},
{"name":"Frank","quote":"Grass-roots well-modulated architecture"},
{"name":"Matthew","quote":"Right-sized incremental core"},
{"name":"Jonathan","quote":"Self-enabling bifurcated encoding"},
{"name":"Louis","quote":"Exclusive scalable neural-net"},
{"name":"Adam","quote":"Re-engineered cohesive matrix"},
{"name":"Roy","quote":"Sharable full-range ability"},
{"name":"Benjamin","quote":"Focused client-driven challenge"},
{"name":"Daniel","quote":"User-friendly zero administration workforce"},
{"name":"Justin","quote":"Multi-channelled incremental frame"},
{"name":"Kenneth","quote":"Versatile secondary emulation"},
{"name":"Christopher","quote":"Distributed fresh-thinking hardware"},
{"name":"Harry","quote":"Configurable optimizing interface"},
{"name":"Justin","quote":"Innovative tangible instruction set"},
{"name":"Kevin","quote":"Phased real-time circuit"},
{"name":"John","quote":"Fully-configurable dynamic capability"},
{"name":"Steven","quote":"Cross-platform 3rd generation help-desk"},
{"name":"Jimmy","quote":"Integrated bandwidth-monitored hub"},
{"name":"Jeremy","quote":"Secured multi-state internet solution"},
{"name":"Earl","quote":"Optimized 5th generation architecture"},
{"name":"Anthony","quote":"Triple-buffered foreground definition"},
{"name":"Peter","quote":"Balanced tangible alliance"},
{"name":"Mark","quote":"Visionary zero tolerance model"},
{"name":"Roy","quote":"Up-sized didactic toolset"},
{"name":"Joseph","quote":"Inverse motivating system engine"},
{"name":"Edward","quote":"Polarised global matrix"},
{"name":"Ralph","quote":"Re-contextualized full-range parallelism"},
{"name":"Jesse","quote":"Multi-channelled holistic methodology"},
{"name":"Louis","quote":"Down-sized coherent implementation"},
{"name":"Billy","quote":"Self-enabling tangible projection"},
{"name":"Kevin","quote":"Innovative disintermediate product"},
{"name":"Ryan","quote":"Re-contextualized disintermediate functionalities"},
{"name":"Stephen","quote":"Devolved zero tolerance hierarchy"},
{"name":"Bruce","quote":"Multi-tiered static core"},
{"name":"Ryan","quote":"Front-line client-driven superstructure"},
{"name":"Donald","quote":"Customer-focused user-facing functionalities"},
{"name":"Samuel","quote":"Team-oriented heuristic flexibility"},
{"name":"David","quote":"Horizontal mobile moderator"},
{"name":"Charles","quote":"Extended bottom-line protocol"},
{"name":"Henry","quote":"Intuitive 24 hour task-force"},
{"name":"George","quote":"Future-proofed transitional time-frame"},
{"name":"Walter","quote":"Synergized transitional implementation"},
{"name":"Donald","quote":"Seamless optimizing open system"},
{"name":"Roger","quote":"Implemented coherent archive"},
{"name":"Douglas","quote":"Organized needs-based neural-net"},
{"name":"Wayne","quote":"Optional global complexity"},
{"name":"Samuel","quote":"Decentralized needs-based matrices"},
{"name":"Raymond","quote":"Implemented contextually-based concept"},
{"name":"Chris","quote":"Future-proofed 6th generation focus group"},
{"name":"Richard","quote":"Total zero defect info-mediaries"},
{"name":"Harry","quote":"Stand-alone local initiative"},
{"name":"Robert","quote":"Assimilated grid-enabled database"},
{"name":"Michael","quote":"Total context-sensitive knowledge base"},
{"name":"Donald","quote":"Integrated foreground budgetary management"},
{"name":"Justin","quote":"Multi-lateral 5th generation complexity"},
{"name":"Johnny","quote":"Mandatory solution-oriented forecast"},
{"name":"Edward","quote":"Horizontal eco-centric Graphic Interface"},
{"name":"Carlos","quote":"Object-based zero defect hierarchy"},
{"name":"Bruce","quote":"Self-enabling regional attitude"},
{"name":"Antonio","quote":"Switchable stable ability"},
{"name":"Willie","quote":"User-centric interactive benchmark"},
{"name":"Harold","quote":"Customer-focused bi-directional groupware"},
{"name":"Albert","quote":"Open-source 3rd generation solution"},
{"name":"Mark","quote":"Expanded empowering forecast"},
{"name":"Craig","quote":"Persevering scalable strategy"},
{"name":"Nicholas","quote":"Devolved coherent open system"},
{"name":"Howard","quote":"Configurable directional matrices"},
{"name":"Roger","quote":"Cross-group demand-driven knowledge base"},
{"name":"Brian","quote":"Team-oriented maximized concept"},
{"name":"Brandon","quote":"Re-contextualized empowering challenge"},
{"name":"Todd","quote":"Cross-group regional hub"},
{"name":"Fred","quote":"Profit-focused maximized time-frame"},
{"name":"Edward","quote":"Exclusive national monitoring"},
{"name":"Samuel","quote":"Proactive high-level projection"},
{"name":"Brian","quote":"Advanced bifurcated strategy"},
{"name":"Willie","quote":"Switchable needs-based alliance"},
{"name":"Kevin","quote":"Upgradable stable capacity"},
{"name":"Frank","quote":"Adaptive bi-directional definition"},
{"name":"Terry","quote":"Mandatory client-driven architecture"},
{"name":"Earl","quote":"Persistent needs-based emulation"},
{"name":"Samuel","quote":"Exclusive executive customer loyalty"},
{"name":"Jerry","quote":"Automated systematic collaboration"},
{"name":"Christopher","quote":"Mandatory holistic benchmark"},
{"name":"Scott","quote":"Ergonomic bandwidth-monitored firmware"},
{"name":"Harold","quote":"Grass-roots bi-directional leverage"},
{"name":"Walter","quote":"Multi-layered fault-tolerant instruction set"},
{"name":"Charles","quote":"Virtual empowering customer loyalty"},
{"name":"Frank","quote":"Synergized real-time core"},
{"name":"Michael","quote":"Cross-platform full-range customer loyalty"},
{"name":"Billy","quote":"Balanced asynchronous service-desk"},
{"name":"Earl","quote":"Public-key solution-oriented circuit"},
{"name":"Steven","quote":"Reactive regional moderator"},
{"name":"John","quote":"Compatible intangible middleware"},
{"name":"Robert","quote":"Synergized object-oriented monitoring"},
{"name":"Philip","quote":"Mandatory cohesive utilisation"},
{"name":"Chris","quote":"Vision-oriented directional hardware"},
{"name":"Martin","quote":"Programmable client-server artificial intelligence"},
{"name":"Donald","quote":"Persistent client-server toolset"},
{"name":"John","quote":"Balanced needs-based methodology"},
{"name":"Adam","quote":"Decentralized asynchronous hub"},
{"name":"Kenneth","quote":"Function-based even-keeled application"},
{"name":"Ernest","quote":"Up-sized zero tolerance complexity"},
{"name":"Martin","quote":"Persevering fresh-thinking knowledge base"},
{"name":"George","quote":"Face to face foreground application"},
{"name":"Jeremy","quote":"Compatible 3rd generation Graphical User Interface"},
{"name":"Gregory","quote":"Mandatory transitional array"},
{"name":"Carlos","quote":"Multi-layered client-server capability"},
{"name":"Russell","quote":"User-centric scalable extranet"},
{"name":"Bruce","quote":"Phased even-keeled emulation"},
{"name":"Howard","quote":"Exclusive bandwidth-monitored moratorium"},
{"name":"James","quote":"Robust zero administration flexibility"},
{"name":"Martin","quote":"Intuitive directional leverage"},
{"name":"Victor","quote":"Reduced mobile array"},
{"name":"Bobby","quote":"Networked intangible orchestration"},
{"name":"Mark","quote":"Customizable multi-tasking firmware"},
{"name":"Steve","quote":"User-centric interactive matrices"},
{"name":"Terry","quote":"Optional attitude-oriented installation"},
{"name":"Joe","quote":"Function-based dedicated capacity"},
{"name":"Carlos","quote":"Sharable even-keeled frame"},
{"name":"Arthur","quote":"Programmable heuristic knowledge base"},
{"name":"Aaron","quote":"Progressive well-modulated project"},
{"name":"Russell","quote":"Self-enabling foreground focus group"},
{"name":"Joe","quote":"Multi-tiered client-server initiative"},
{"name":"Michael","quote":"Public-key user-facing core"},
{"name":"Craig","quote":"Down-sized motivating application"},
{"name":"Andrew","quote":"Intuitive local middleware"},
{"name":"Lawrence","quote":"Organized fresh-thinking algorithm"},
{"name":"Phillip","quote":"Object-based mission-critical core"},
{"name":"Eugene","quote":"Customizable didactic superstructure"},
{"name":"Samuel","quote":"Right-sized secondary migration"},
{"name":"Benjamin","quote":"Down-sized motivating access"},
{"name":"Jose","quote":"Re-contextualized interactive emulation"},
{"name":"Aaron","quote":"Expanded multi-tasking capacity"},
{"name":"Gregory","quote":"Networked regional success"},
{"name":"Fred","quote":"Multi-lateral holistic capability"},
{"name":"William","quote":"Cloned fresh-thinking core"},
{"name":"Todd","quote":"Secured value-added function"},
{"name":"Robert","quote":"Implemented 24 hour hardware"},
{"name":"Joe","quote":"Quality-focused well-modulated core"},
{"name":"Steven","quote":"Monitored reciprocal solution"},
{"name":"Stephen","quote":"Proactive motivating framework"},
{"name":"Gregory","quote":"Stand-alone empowering challenge"},
{"name":"Benjamin","quote":"Self-enabling executive hardware"},
{"name":"Kenneth","quote":"Horizontal full-range pricing structure"},
{"name":"Richard","quote":"Optional real-time local area network"},
{"name":"Russell","quote":"Monitored asynchronous info-mediaries"},
{"name":"James","quote":"Up-sized asymmetric open system"},
{"name":"Andrew","quote":"Extended client-driven conglomeration"},
{"name":"Randy","quote":"Business-focused zero administration knowledge base"},
{"name":"Antonio","quote":"Virtual heuristic intranet"},
{"name":"Andrew","quote":"Fundamental dedicated benchmark"},
{"name":"Paul","quote":"Secured even-keeled groupware"},
{"name":"Joseph","quote":"Decentralized 6th generation matrices"},
{"name":"Harold","quote":"Switchable 4th generation migration"},
{"name":"Jerry","quote":"Diverse full-range approach"},
{"name":"Jack","quote":"Exclusive bottom-line flexibility"},
{"name":"Jason","quote":"Monitored zero defect analyzer"},
{"name":"Philip","quote":"Proactive 24/7 migration"},
{"name":"Joe","quote":"Organized methodical matrix"},
{"name":"Jason","quote":"Pre-emptive regional frame"},
{"name":"Jason","quote":"Cloned mobile concept"},
{"name":"Larry","quote":"Secured actuating model"},
{"name":"Jason","quote":"Open-architected 3rd generation workforce"},
{"name":"Billy","quote":"Integrated interactive capability"},
{"name":"Timothy","quote":"Digitized context-sensitive initiative"},
{"name":"Steven","quote":"Progressive reciprocal database"}];

	// jsonArray.forEach(doucment => {
	// 	db.collection(table).save(doucment);
	// 	console.log('salvo no banco de dados: ' + doucment);
	// })

	db.collection(table).insert(jsonArray);

	res.send('Banco cheio! =)');
});

app.get('/quotes/api', (req, res) => {
	var cursor = db.collection(table).find();
	cursor.toArray((err, results) => {
		if(err)
			return console.error(err);

		var random = Math.floor(Math.random() * results.length)

		var singleQuote = results[random];
		res.send(singleQuote);
	})
});